name: C Build Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Hello World
        run: gcc -o hello_executable main.c

      - name: Save executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary   # The name of the download folder
          path: hello_executable  # The file you want to save