

name: C Build Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Hello World
        run: gcc -o hello_executable main.c

      - name: Run Post-Build Scripts
        run: |
          chmod +x ./post.sh
          ./post.sh
      - name: Save Release Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          # Pointing this to the folder created in post.sh
          path: releases/